version: "3.8"
services:
  account:
    restart: always
    build:
      context: services/account
    image: hatena-intern-2020-account
    ports:
      - 51051:50051
    environment:
      GRPC_PORT: "50051"
      ECDSA_PRIVATE_KEY_FILE: "/secret/ecdsa-private.pem"
      MODE: "development"
      DATABASE_DSN: "root@(account-db:3306)/intern_2020_account?time_zone=UTC&parseTime=true&loc=UTC"
    volumes:
      - ./k8s/account/secret:/secret
  account-db:
    image: mysql:8.0
    command: --lower-case-table-names=1
    ports:
      - 13306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
      TZ: "UTC"
    volumes:
      - ./k8s/account/config:/config
      - ./docker-compose/init-account-db.sh:/docker-entrypoint-initdb.d/init-account-db.sh
      - ./db/account/mysql:/var/lib/mysql:delegated
  blog:
    restart: always
    build:
      context: services/blog
    image: hatena-intern-2020-blog
    ports:
      - 8080:8080
    environment:
      PORT: "8080"
      ACCOUNT_ECDSA_PUBLIC_KEY_FILE: "/secret/account-ecdsa-public.pem"
      MODE: "development"
      DATABASE_DSN: "root@(blog-db:3306)/intern_2020_blog?time_zone=UTC&parseTime=true&loc=UTC"
      ACCOUNT_ADDR: "account:50051"
      RENDERER_ADDR: "renderer-go:50051"
    volumes:
      - ./k8s/blog/secret:/secret
  blog-db:
    image: mysql:8.0
    command: --lower-case-table-names=1
    ports:
      - 13307:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
      TZ: "UTC"
    volumes:
    - ./k8s/blog/config:/config
    - ./docker-compose/init-blog-db.sh:/docker-entrypoint-initdb.d/init-blog-db.sh
    - ./db/blog/mysql:/var/lib/mysql:delegated
  renderer-go:
    restart: always
    build:
      context: services/renderer-go
    image: hatena-intern-2020-renderer-go
    ports:
      - 52052:50051
    environment:
      GRPC_PORT: "50051"
      MODE: "development"
